[prestashop]
api_url = "http://localhost:8001/api"
api_key = "SLZAZMME7IRMFDDJFCQZ4QUJCEEF68P2"
admin_url = "http://localhost:8001/admin-dev"

[import]
products_limit = 5
product_quantity = 9
active = true

[paths]
results_dir = "scraper/results"
images_dir = "scraper/results/images"

[files]
categories_file = "categories.json"
products_file = "products_detailed.json"