[prestashop]
api_url = "http://localhost:8080/api"
api_key = "PW2SHEF9YRJ8TG8NXQF1EKZU2I16JGGC"
admin_url = "http://localhost:8080/admin_folder"

[import]
products_limit = 5
product_quantity = 9
active = true

[paths]
results_dir = "scraper/results"

[files]
categories_file = "categories.json"
products_file = "products_detailed.json"