[prestashop]
api_url = "https://localhost/api"
api_key = "SLZAZMME7IRMFDDJFCQZ4QUJCEEF68P2"
admin_url = "https://localhost/admin-dev"
verify_ssl = false

[import]
HOME_CATEGORY_ID = 2
products_limit = 1000
product_quantity_range = [0, 10]  # min, max
vat_rate = 0.23
active = true
MAX_WORKERS = 6

[paths]
results_dir = "scraper/results"
images_dir = "scraper/results/images"

[files]
categories_file = "categories.json"
products_file = "products_detailed.json"